[build]
  publish = "frontend/dist"
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "frontend/netlify/functions"

# Redirections pour l'API vers les fonctions Netlify
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "/.netlify/functions"

[context.deploy-preview.environment]
  VITE_API_URL = "/.netlify/functions"
