[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'postgresql', 'gcc', 'nodejs']

[phases.install]
cmds = [
  'cd backend && pip install --break-system-packages -r requirements.txt',
  'cd frontend && npm ci --legacy-peer-deps'
]

[phases.build]
cmds = [
  'cd frontend && npm run build',
  'cd backend && mkdir -p staticfiles',
  'cd backend && python manage.py collectstatic --noinput --clear'
]

[start]
cmd = 'cd backend && python manage.py migrate --noinput && python -m gunicorn jaelleshop.wsgi:application --bind 0.0.0.0:$PORT' 