[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install --break-system-packages -r requirements.txt && python manage.py collectstatic --noinput && cd ../frontend && npm ci --legacy-peer-deps && npm run build && cd ../backend && mkdir -p staticfiles"

[deploy]
startCommand = "cd backend && python manage.py migrate --noinput && python -m gunicorn jaelleshop.wsgi:application --bind 0.0.0.0:$PORT --workers=1 --timeout=120"
healthcheckPath = "/status/"
healthcheckTimeout = 300
provider = "nixpacks"
noDocker = true

[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'postgresql', 'gcc', 'nodejs']

[[services]]
name = "backend"
envs = { STATIC_DIR = "../frontend/dist" }

[[volumes]]
name = "postgres_data"
mountPath = "/var/lib/postgresql/data"
engine = "postgres" 